services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    volumes:
      -./storage/mysql:/var/lib/mysql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "localhost", "-u", "root", "p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      -"50778:3306"
  glpi:
    image: elestio/glpi:11.0.6
    container_name: glpi
    restart: always
    hostname: glpi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./env
    
    environment:
      - TIMEZONE=Europe/Brussels
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/files:/var/glpi/files
      - ./storage/var/www/html/glpi/config:/var/glpi/config
      - ./storage/glpi_marketplace:/var/www/glpi/glpi_marketplace
  glpi-mcp:
    image: quay.io/karmab/glpic
    container_name: glpi-mcp
    restart: always
    entrypoint: /usr/local/bin/glpimcp 
    ports:
      -"8000:8000"
    environment:
      - GLPI_URL=http://glpi/apirest.php
      - GLPI_USER=${GLPI_MCP_USER}
      - GLPI_TOKEN={GLPI_MCP_TOKEN}
    depends_on:
      glpi:
        condition: service_healthy

  ollama:
    image: ollama:ollama
    container_name: ollama
    restart: always
    volumes:
      -./storage/ollama:/root/.ollama

  chatbot-api:
    image: node:20-alpine
    container_name: chatbot-api
    restart: always
    working_dir: /app
    volumes:
      -./chatbot-api:/app
    command: sh -c "npm install && node server.js"
    environment:
      - GLPI_URL=http://glpi/apirest.php
      - APP_TOKEN=${GLPI_APP_TOKEN}
      - USER_TOKEN=${GLPI_USER_TOKEN}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_KEY=${OLLAMA_KEY}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    depends_on:
      glpi:
        condition: service_healthy

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - "22811:80"
    environment:
      - PMA_HOST: MYSQL
      - PMA_PORT: 3306
      - PMA_USER: root
      - PMA_PASSWORD: ${ADMIN_PASSWORD}
      - UPLOAD_LIMIT: 500M
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
      - "40443:443"
    volumes:
      -./nginx:etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./chatbot:/var/www/html/chatbot

    depends_on:
      glpi:
        condition: service_healthy