events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream php_backends {
        server backend1:9000;
        server backend2:9000;
    }

    server {
        listen 80;
        server_name aromaris.org www.aromaris.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name aromaris.org www.aromaris.org;

        # Rutas corregidas para tus certificados autofirmados locales
        ssl_certificate /etc/nginx/certs/aromaris.crt;
        ssl_certificate_key /etc/nginx/certs/aromaris.key;

        root /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass php_backends;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
