services:
  passbolt-db:
    image: mariadb:10.11
    container_name: passbolt-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: ${PASSBOLT_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${PASSBOLT_DB_NAME}
      - MYSQL_USER: ${PASSBOLT_DB_USER}
      - MYSQL_PASSWORD: ${PASSBOLT_DB_PASSWORD}

    volumes:
      - ./storage/passbolt-db:/var/lib/mysql
      - ./certs/passbolt.pem:/etc/ssl/certs/certificate.crt
      - ./certs/passbolt.pem:/etc/ssl/certs/certificate.key
    healthcheck:
      test: ["CDM", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${PASSBOLT_DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt
    restart: always
    depends_on:
      passbolt-db:
        condition: service_healthy
    environment:
      - APP_FULL_BASE_URL: https://passbolt.aromaris.local
      - DATASOURCES_DEFAULT_HOST: passbolt-db
      - DATASOURCES_DEFAULT_USERNAME: ${PASSBOLT_DB_USER}
      - DATASOURCES_DEFAULT_PASSWORD: ${PASSBOLT_DB_PASSWORD}
      - DATASOURCES_DEFAULT_DATABASE: ${PASSBOLT_DB_NAME}
      - EMAIL_TRANSPORT_DEFAULT_HOST: ${PASSBOLT_SMTP_HOST}
      - EMAIL_TRANSPORT_DEFAULT_PORT: ${PASSBOLT_SMTP_PORT}
      - EMAIL_TRANSPORT_DEFAULT_USERNAME: ${PASSBOLT_SMTP_USER}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD: ${PASSBOLT_SMTP_PASSWORD}
      - EMAIL_TRANSPORT_DEFAULT_TLS: "true"
      - EMAIL_DEFAULT_FROM: ${PASSBOLT_EMAIL_FROM}
    volumes:
      - ./storage/passbolt/gpg:/etc/passbolt/gpg
      - ./storages/passbolt/jwt:/etc/passbolt/jwt
    ports:
      - "8080:80"
      - "4443:443"