services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /home/aromaris/glpi/chatbot:/var/www/html/chatbot
    networks:
      - glpi_default
      - passbolt_default

networks:
  glpi_default:
    external: true
    name: glpi_default
  passbolt_default:
    external: true
    name: passbolt_default


